[package]
name = "rusty-razor"
version = "0.1.0"
authors = ["Salman Saghafi <salman.saghafi@me.com>"]
edition = "2018"

[dependencies]
itertools = "0.7.8"
nom = "^4.1"
criterion = "0.1.2"

[[bench]]
name = "perf_test"
harness = false